// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbjfoupfoefbzfkvkdol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiamZvdXBmb2VmYnpma3ZrZG9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODk3MjAsImV4cCI6MjA2NTQ2NTcyMH0.n9aOp3f1QbQq-yRFmyO0FY9iOCsv4wX0AcZeH0Z0xNQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);